Repository TopAcademy2022/user-monitoring-gui, pull requests merged in 2024-03, with the labels that each got.

#24 Implemented the PrintMenu method. Closed #3
  user-monitoring/Services/ConsoleUserInterface.cs
Labels: enhancement

#26 Implemented the AddProgram method. Closed #15
  user-monitoring/Models/ProgramBanList.cs
Labels: enhancement

#27 Implemented the RemoveProgram method. Closed #16
  user-monitoring/Models/ProgramBanList.cs
Labels: enhancement

#32 Implemented the AddWord method. Closed #28
  user-monitoring/Models/WordBanList.cs
Labels: enhancement

#33 Implemented the RemoveWord method. Closed #29
  user-monitoring/Models/WordBanList.cs
Labels: enhancement

#35 Added server connection. Closed #22
  .gitignore
  docs/Doxyfile
  user-monitoring-gui.sln
  user-monitoring-gui/Models/Network/ServerResponse.cs
  user-monitoring-gui/Models/Network/ServerStatusCode.cs
  user-monitoring-gui/Models/ProgramBanList.cs
  user-monitoring-gui/Models/Setting.cs
  user-monitoring-gui/Models/WordBanList.cs
  user-monitoring-gui/Program.cs
  user-monitoring-gui/Services/ConsoleUserInterface.cs
  user-monitoring-gui/Services/Interfaces/IKeyboardKeysReader.cs
  user-monitoring-gui/Services/Interfaces/IProgramBanListService.cs
  user-monitoring-gui/Services/Interfaces/IRunProgramReader.cs
  user-monitoring-gui/Services/Interfaces/IServerRequest.cs
  user-monitoring-gui/Services/Interfaces/IUserInterface.cs
  user-monitoring-gui/Services/Interfaces/IWordBanListService.cs
  user-monitoring-gui/Services/KeyboardKeysReader.cs
  user-monitoring-gui/Services/ProgramBanListService.cs
  user-monitoring-gui/Services/ProhibitedConductManager.cs
  user-monitoring-gui/Services/RunProgramReader.cs
  user-monitoring-gui/Services/WordBanListService.cs
  user-monitoring-gui/user-monitoring-gui.csproj
Labels: documentation, enhancement

#37 Added tests for ProgramBanList. Closed #36
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests.sln
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests/GlobalUsings.cs
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests/ProgramBanListTest.cs
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests/user-monitoring-gui-tests.csproj
  user-monitoring-gui.sln
Labels: documentation, enhancement, testing

#39 Implemented the SaveWordBanList method. Closed #34
  user-monitoring-gui/Program.cs
  user-monitoring-gui/Services/Data Storage Area.cs
  user-monitoring-gui/Services/Interfaces/IWordBanListService.cs
  user-monitoring-gui/Services/WordBanListService.cs
Labels: documentation, enhancement

#42 Added tests for RunProgramReader. Closed #41
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests/RunProgramReaderTest.cs
Labels: documentation, enhancement, testing

#43 Added tests for WordBanList. Closed #40
  Tests/user-monitoring-gui-tests/user-monitoring-gui-tests/WordBanListTest.cs
  user-monitoring-gui/Models/WordBanList.cs
  user-monitoring-gui/Services/WordBanListService.cs
Labels: documentation, enhancement, testing

#46 Implemented the PrintMenuSettings method. Closed #4
  user-monitoring-gui/Services/ConsoleUserInterface.cs
Labels: enhancement

#47 Added Github action. Closed #44
  .github/workflows/dotnet-desktop.yml
Labels: enhancement, testing

#52 Updated KillProgram method. Closed #30
  user-monitoring-gui/Services/RunProgramReader.cs
Labels: documentation, enhancement

#55 Updated IServerRequest. Closed #50
  user-monitoring-gui/Services/Interfaces/IServerRequest.cs
Labels: enhancement

#54 Implemented the PrintMenuWordBanList method. Closed #25
  user-monitoring-gui/Services/ConsoleUserInterface.cs
Labels: enhancement
